version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: release-train-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: release_train
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
